# Generated by Django 5.0.4 on 2024-04-29 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_artwork_artist_alter_messagethread_buyer_and_more'),
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks_bought', to='myauth.userprofile'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks_created', to='myauth.userprofile'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_message_threads', to='myauth.userprofile'),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_message_threads', to='myauth.userprofile'),
        ),
    ]
