# Generated by Django 5.0.4 on 2024-05-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_artwork_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='current_highest_bid',
        ),
    ]
