# Generated by Django 5.0.4 on 2024-05-01 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_artwork_current_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='gallery.artwork'),
        ),
    ]
