# Generated by Django 5.0.4 on 2024-05-02 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_bid_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkimage',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.artwork'),
        ),
    ]
