# Generated by Django 5.0.4 on 2024-05-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_artwork_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='viewers_count',
            field=models.IntegerField(default=0),
        ),
    ]
