# Generated by Django 5.0.4 on 2024-05-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_artwork_viewers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
