# Generated by Django 5.0.4 on 2024-05-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_artwork_sold_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredartowrk',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='featuredartowrk',
            name='featured_on',
        ),
        migrations.AddField(
            model_name='featuredartowrk',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='featuredartowrk',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
