# Generated by Django 5.0.4 on 2024-05-16 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_featuredartowrk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredartowrk',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
