# Generated by Django 5.0.4 on 2024-05-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_artworknotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='gallery.artwork'),
        ),
    ]
