# Generated by Django 5.0.4 on 2024-05-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0006_remove_user_name_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
