# Generated by Django 5.0.4 on 2024-05-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0007_alter_user_about_alter_user_achievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='location',
        ),
    ]
