# Generated by Django 5.0.4 on 2024-05-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_rename_address_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Seller'), (1, 'Buyer')], default=1, null=True),
        ),
    ]
