# Generated by Django 5.0.4 on 2024-05-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0009_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
